version: "3"

services:
  frontend:
    build:
      context: ./chat
      dockerfile: Dockerfile
      args:
        - VITE_APP_DOMEN_PORT=localhost:3000
        - VITE_APP_PROTOCOL=ws
    ports:
      - "81:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./chat_api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
