name: build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Качаю репозиторий
        uses: actions/checkout@v2
      - name: Задаю переменные окружения из секрета
        env:
          DOCKER_COMPOSE_ENV: ${{ secrets.DOCKER_COMPOSE_ENV }}
        run: echo "$DOCKER_COMPOSE_ENV" > .env
        run: echo "$DOCKER_COMPOSE_ENV_BACKEND" > chat_api/.env.production
      - name: Build the stack
        run: docker-compose up -d
      - name: Захожу на VPS и деплою
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/chat_app
