name: build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Копирую папку на VPS сервер
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: /var/www/chat_app
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          rmRemote: true
      - name: Захожу на VPS и запускаю сборку образа
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/chat_app/chat_api
            echo "${{ secrets.ENV_BACKEND }}" > .env.development
            cd /var/www/chat_app
            docker stop chat_app-backend-1
            docker stop chat_app-frontend-1
            docker stop chat_app-database-1
            docker container prune -f
            docker image prune -f
            docker builder prune -f
            docker-compose up -d
